# -*- coding: utf-8 -*-
"""Blog_generator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YdC776n3_PURxtP9dYDPgzKc2HSb4j7i
"""

!pip install transformers

from transformers import GPT2LMHeadModel, GPT2Tokenizer

tokenizer = GPT2Tokenizer.from_pretrained('gpt2')

model = GPT2LMHeadModel.from_pretrained('gpt2', pad_token_id = tokenizer.eos_token_id)

sentence = "I love chocolates."
input_ids = tokenizer.encode(sentence, return_tensors='pt')

output = model.generate(input_ids, max_length = 130, num_beams = 5, no_repeat_ngram_size= 2, early_stopping= True)

tokenizer.decode(output[0], skip_special_tokens =True)

